### ISSUE TITLE
Can't this library be used without an id?

### ISSUE THREAD

**Issue by elieobeid7** [oscarotero/simple-crud#35]
My company has created mysql table which has a `videos` table, inside, you'll find `video_id` not `id`

if I do

```
  $videos = $db->videos->select()->run();
    print_r($videos);
```

I get

```
Notice: Undefined index: id in C:\xampp\htdocs\project\vendor\simple-crud\simple-crud\src\Table.php on line 419

Fatal error: Uncaught exception 'SimpleCrud\SimpleCrudException' with message 'Undefined property 

"id"' in C:\xampp\htdocs\project\vendor\simple-crud\simple-crud\src\Row.php:105 Stack trace: #0 

C:\xampp\htdocs\project\vendor\simple-crud\simple-crud\src\Table.php(73): SimpleCrud\Row->__get('id') 

#1 C:\xampp\htdocs\project\vendor\simple-crud\simple-crud\src\Table.php(433): SimpleCrud\Table->cache(Object(SimpleCrud\Row)) #2 C:\xampp\htdocs\project\vendor\simple-crud\simple-crud\src\Queries\Mysql\Select.php(151): SimpleCrud\Table->createFromDatabase(Array) #3 

C:\xampp\htdocs\project\vendor\simple-crud\simple-crud\src\Queries\Mysql\Select.php(117): 

SimpleCrud\Queries\Mysql\Select->createRow(Array) #4 C:\xampp\htdocs\project\index.php(15): 

SimpleCrud\Queries\Mysql\Select->run() #5 {main} thrown in C:\xampp\htdocs\project\vendor\simple-crud\simple-crud\src\Row.php on line 105


```

**Comment by oscarotero** [comment]
Hi.
No, at this moment, is required to have the field `id` because it's required to identify each row, fetch relations, etc.
